[package]
name = "rust_tracer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst = "0.15.3"
ncollide3d = "0.32.0"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
